// This file was auto-generated by ML.NET Model Builder.
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace ComputerPredictor
{
    public partial class OperatingSystem
    {
        /// <summary>
        /// model input class for OperatingSystemModel.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [LoadColumn(0)]
            [ColumnName(@"cpu_speed_ghz")]
            public float Cpu_speed_ghz { get; set; }

            [LoadColumn(1)]
            [ColumnName(@"cpu_cores")]
            public float Cpu_cores { get; set; }

            [LoadColumn(2)]
            [ColumnName(@"ram_gb")]
            public float Ram_gb { get; set; }

            [LoadColumn(3)]
            [ColumnName(@"storage_type")]
            public string Storage_type { get; set; }

            [LoadColumn(4)]
            [ColumnName(@"storage_gb")]
            public float Storage_gb { get; set; }

            [LoadColumn(5)]
            [ColumnName(@"operating_system")]
            public string Operating_system { get; set; }

            [LoadColumn(6)]
            [ColumnName(@"target_use_case")]
            public string Target_use_case { get; set; }

            [LoadColumn(7)]
            [ColumnName(@"price_usd")]
            public float Price_usd { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for OperatingSystemModel.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"cpu_speed_ghz")]
            public float Cpu_speed_ghz { get; set; }

            [ColumnName(@"cpu_cores")]
            public float Cpu_cores { get; set; }

            [ColumnName(@"ram_gb")]
            public float Ram_gb { get; set; }

            [ColumnName(@"storage_type")]
            public float[] Storage_type { get; set; }

            [ColumnName(@"storage_gb")]
            public float Storage_gb { get; set; }

            [ColumnName(@"operating_system")]
            public uint Operating_system { get; set; }

            [ColumnName(@"target_use_case")]
            public float[] Target_use_case { get; set; }

            [ColumnName(@"price_usd")]
            public float Price_usd { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"PredictedLabel")]
            public string PredictedLabel { get; set; }

            [ColumnName(@"Score")]
            public float[] Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath(Path.Combine("MLModels", "OperatingSystem.mlnet"));


        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);


        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }

        /// <summary>
        /// Use this method to predict scores for all possible labels.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static IOrderedEnumerable<KeyValuePair<string, float>> PredictAllLabels(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            var result = predEngine.Predict(input);
            return GetSortedScoresWithLabels(result);
        }

        /// <summary>
        /// Map the unlabeled result score array to the predicted label names.
        /// </summary>
        /// <param name="result">Prediction to get the labeled scores from.</param>
        /// <returns>Ordered list of label and score.</returns>
        /// <exception cref="Exception"></exception>
        public static IOrderedEnumerable<KeyValuePair<string, float>> GetSortedScoresWithLabels(ModelOutput result)
        {
            var unlabeledScores = result.Score;
            var labelNames = GetLabels(result);

            Dictionary<string, float> labledScores = new Dictionary<string, float>();
            for (int i = 0; i < labelNames.Count(); i++)
            {
                // Map the names to the predicted result score array
                var labelName = labelNames.ElementAt(i);
                labledScores.Add(labelName.ToString(), unlabeledScores[i]);
            }

            return labledScores.OrderByDescending(c => c.Value);
        }

        /// <summary>
        /// Get the ordered label names.
        /// </summary>
        /// <param name="result">Predicted result to get the labels from.</param>
        /// <returns>List of labels.</returns>
        /// <exception cref="Exception"></exception>
        private static IEnumerable<string> GetLabels(ModelOutput result)
        {
            var schema = PredictEngine.Value.OutputSchema;

            var labelColumn = schema.GetColumnOrNull("operating_system");
            if (labelColumn == null)
            {
                throw new Exception("operating_system column not found. Make sure the name searched for matches the name in the schema.");
            }

            // Key values contains an ordered array of the possible labels. This allows us to map the results to the correct label value.
            var keyNames = new VBuffer<ReadOnlyMemory<char>>();
            labelColumn.Value.GetKeyValues(ref keyNames);
            return keyNames.DenseValues().Select(x => x.ToString());
        }

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }
    }
}
