// This file was auto-generated by ML.NET Model Builder.
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace ComputerPredictor
{
    public partial class PriceUsd
    {
        /// <summary>
        /// model input class for PriceUsd.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [LoadColumn(0)]
            [ColumnName(@"cpu_speed_ghz")]
            public float Cpu_speed_ghz { get; set; }

            [LoadColumn(1)]
            [ColumnName(@"cpu_cores")]
            public float Cpu_cores { get; set; }

            [LoadColumn(2)]
            [ColumnName(@"ram_gb")]
            public float Ram_gb { get; set; }

            [LoadColumn(3)]
            [ColumnName(@"storage_type")]
            public string Storage_type { get; set; }

            [LoadColumn(4)]
            [ColumnName(@"storage_gb")]
            public float Storage_gb { get; set; }

            [LoadColumn(5)]
            [ColumnName(@"operating_system")]
            public string Operating_system { get; set; }

            [LoadColumn(6)]
            [ColumnName(@"target_use_case")]
            public string Target_use_case { get; set; }

            [LoadColumn(7)]
            [ColumnName(@"price_usd")]
            public float Price_usd { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for PriceUsd.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"cpu_speed_ghz")]
            public float Cpu_speed_ghz { get; set; }

            [ColumnName(@"cpu_cores")]
            public float Cpu_cores { get; set; }

            [ColumnName(@"ram_gb")]
            public float Ram_gb { get; set; }

            [ColumnName(@"storage_type")]
            public float[] Storage_type { get; set; }

            [ColumnName(@"storage_gb")]
            public float Storage_gb { get; set; }

            [ColumnName(@"operating_system")]
            public float[] Operating_system { get; set; }

            [ColumnName(@"target_use_case")]
            public float[] Target_use_case { get; set; }

            [ColumnName(@"price_usd")]
            public float Price_usd { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"Score")]
            public float Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath(Path.Combine("MLModels", "PriceUsd.mlnet"));

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);


        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }
    }
}
